# Generated by Django 3.0.3 on 2020-03-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathnotebook',
            options={'ordering': ['-created_on']},
        ),
    ]
