# Generated by Django 3.0.3 on 2020-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(default='#'),
        ),
    ]
