# Generated by Django 3.0.3 on 2020-03-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200323_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default="{% static '/img/wolf-logo_D5.png' %}", upload_to='project_pics'),
        ),
    ]
